var PERSONALITIES = [
  {
    code: "lezeren",
    name: "乐子人",
    emoji: "🤪",
    rarity: "常见",
    cluster: "highEnergy",
    pattern: { N: "H", E: "H", A: "H", Ac: "H" },
    desc: "你是网络世界的永动机。你的存在本身就是一场大型真人秀。",
    common_comments: ["群里最活跃的那个就是你", "每天都能看到你在各种评论区出没"],
    traits: ["段子手","气氛组","话题制造机","社交悍匪","开心果","整活大师"],
    suggestions: "继续保持你的活力，但偶尔也留点空间给内向的朋友们喘口气。"
  },
  {
    code: "qianshuiting",
    name: "潜水艇",
    emoji: "🤿",
    rarity: "常见",
    cluster: "introvert",
    pattern: { N: "M", E: "L", A: "L", Ac: "L" },
    desc: "你常年在线，但几乎不发声。",
    common_comments: ["你还在群里吗？", "默默围观全世界的吃瓜专业户"],
    traits: ["深度潜水","信息收集者","沉默围观者","已读不回大师","低调之王"],
    suggestions: "你的沉默是一种力量，但适当地冒泡会让你的存在更有意义。"
  },
  {
    code: "saibopusa",
    name: "赛博菩萨",
    emoji: "🙏",
    rarity: "稀有",
    cluster: "social",
    pattern: { N: "H", E: "M", A: "L", Ac: "H", So: "H" },
    desc: "你是网络世界的一股清流，也是所有群聊里的定海神针。",
    common_comments: ["你真的是管理员吗？", "群里的和事佬"],
    traits: ["网络义工","资源分享家","群聊定海神针","和事佬","知识库"],
    suggestions: "你的善良是稀缺资源，请务必珍惜自己的能量。"
  },
  {
    code: "dianzicangshu",
    name: "电子仓鼠",
    emoji: "🐹",
    rarity: "常见",
    cluster: "introvert",
    pattern: { N: "H", E: "L", A: "L", Ac: "M" },
    desc: "你就是互联网的末代皇帝——把整个互联网往硬盘里搬的那种。",
    common_comments: ["你有没有XX资源？", "你的网盘容量是别人的好几倍"],
    traits: ["收藏家","网盘囤积症","资源帝","以后再看型人格","移动硬盘"],
    suggestions: "偶尔清理一下你的收藏夹吧，给未来的自己减负。"
  },
  {
    code: "fuduji",
    name: "复读机",
    emoji: "🔁",
    rarity: "常见",
    cluster: "highEnergy",
    pattern: { N: "M", E: "H", A: "M", Ac: "M" },
    desc: "你是群聊里最欢乐的存在——因为你说的话90%都是在复读别人。",
    common_comments: ["+1是你最常用的词", "保持队形这件事你是专业的"],
    traits: ["+1专业户","队形守护者","复读之王","群聊气氛组","刷屏高手"],
    suggestions: "复读是快乐的，但偶尔也可以做那个打破队形的人。"
  },
  {
    code: "gangjingshengti",
    name: "杠精圣体",
    emoji: "⚔️",
    rarity: "稀有",
    cluster: "logical",
    pattern: { A: "H", E: "M", N: "M" },
    desc: "你是网络辩论界的无冕之王。",
    common_comments: ["我说一句你顶十句", "评论区的辩论区永远有你的身影"],
    traits: ["逻辑纠察队","辩论狂魔","理性讨论爱好者","逻辑猎犬","论战达人"],
    suggestions: "你的思辨能力是一把双刃剑，用好了很强，用歪了就是杠精。"
  },
  {
    code: "shekongbenkong",
    name: "社恐本恐",
    emoji: "😶‍🌫️",
    rarity: "常见",
    cluster: "introvert",
    pattern: { So: "L", E: "L", Ac: "L" },
    desc: "你在网上的存在方式就是：能文字绝不语音。",
    common_comments: ["你怎么从来不在群里说话？", "你的朋友圈像一座寂静的博物馆"],
    traits: ["独处爱好者","文字交流派","视频通话抗拒者","安静的美男子/女子","节能型人格"],
    suggestions: "独处是充电，但偶尔的社交是放电——两者需要一个平衡。"
  },
  {
    code: "wangluojieliu",
    name: "网络街溜子",
    emoji: "🚶",
    rarity: "常见",
    cluster: "highEnergy",
    pattern: { Ac: "H", E: "M", N: "H" },
    desc: "你是网络世界的游牧民族——没有固定的领地，但每个角落都有你路过的痕迹。",
    common_comments: ["你怎么什么都知道一点？", "你的手机里装了所有主流app"],
    traits: ["信息游牧民族","跨平台迁徙者","广度型选手","路过专业户","什么都懂一点"],
    suggestions: "你的知识广度是优势，但偶尔也需要深潜一下。"
  },
  {
    code: "gengwang",
    name: "梗王",
    emoji: "👑",
    rarity: "稀有",
    cluster: "highEnergy",
    pattern: { E: "H", E_create: "H", A: "M" },
    desc: "你是朋友圈里的段子手天花板。",
    common_comments: ["你的朋友圈比春晚好看", "每次你发动态都有大批人等着截图"],
    traits: ["段子手天花板","语言艺术家","朋友圈年度最佳","金句制造机","幽默大师"],
    suggestions: "你的幽默感是天赋，但不要把自己困在搞笑者的角色里。"
  },
  {
    code: "saibokaogu",
    name: "赛博考古家",
    emoji: "🏺",
    rarity: "稀有",
    cluster: "logical",
    pattern: { N: "H", Ac_explore: "H", E: "M" },
    desc: "你是互联网世界的考古学家——只不过你挖掘的不是恐龙化石，而是十年前的古早帖子。",
    common_comments: ["你是怎么找到这个的？？", "你的搜索能力让人怀疑你是不是有特殊权限"],
    traits: ["信息溯源者","古早帖挖掘机","搜索大师","真相追踪者","赛博福尔摩斯"],
    suggestions: "你的信息检索能力是一种硬核技能，在工作学习中价值连城。"
  },
  {
    code: "yidubuhui",
    name: "已读不回大师",
    emoji: "👻",
    rarity: "常见",
    cluster: "introvert",
    pattern: { So: "M", Ac: "L", E: "L" },
    desc: "你是聊天记录里最令人抓狂的存在——不是因为你说了什么，而是因为你什么都不说。",
    common_comments: ["你终于回我了！", "你的聊天记录里有一半是抱歉刚看到"],
    traits: ["已读不回","回复拖延症","看了等于回了","低回复率","失踪人口"],
    suggestions: "可以尝试看到消息后先发一个表情包。"
  },
  {
    code: "renshesheji",
    name: "人设管理师",
    emoji: "🎭",
    rarity: "稀有",
    cluster: "social",
    pattern: { So_identity: "H", E: "M", Ac: "M" },
    desc: "你在网络上拥有不止一个身份——每一个号都是精心设计的人设。",
    common_comments: ["你有几个号？", "你的每一个号都像完全不同的人"],
    traits: ["多号管理","人设设计师","印象管理大师","身份切换自如","赛博演员"],
    suggestions: "管理多个人设是一项技能，但也要警惕人设疲劳。"
  },
  {
    code: "shenyeemo",
    name: "深夜emo诗人",
    emoji: "🌙",
    rarity: "常见",
    cluster: "social",
    pattern: { E: "H", N: "H", A: "L" },
    desc: "白天的你是一个正常的人类，深夜的你是一个感性的诗人。",
    common_comments: ["你是不是又没睡？", "你的朋友圈白天和深夜完全是两个风格"],
    traits: ["深夜诗人","情感丰富","白天理性夜晚感性","朋友圈情绪日记","emo但可爱"],
    suggestions: "你的深夜文字其实很有价值——与其每次都删除，不如整理成私密日记。"
  },
  {
    code: "chiguayixian",
    name: "吃瓜一线",
    emoji: "🍉",
    rarity: "常见",
    cluster: "highEnergy",
    pattern: { Ac: "H", N: "H", E: "M" },
    desc: "你是网络世界的战地记者——哪里有大瓜，哪里就有你。",
    common_comments: ["你这么快就知道了？！", "你的信息获取速度让人怀疑你是不是有时光机"],
    traits: ["战地记者","热点雷达","吃瓜专业户","信息第一响应者","新闻嗅觉"],
    suggestions: "你的信息追踪能力可以转化为真正有价值的能力。"
  },
  {
    code: "saibopanquan",
    name: "赛博判官",
    emoji: "⚖️",
    rarity: "稀有",
    cluster: "logical",
    pattern: { A: "H", A_critic: "H", E: "M", N: "M" },
    desc: "你是网络世界的民间法官——虽然没有人给你发工资，但你每天都在网上审判各种是非对错。",
    common_comments: ["你又开始判案了", "你的评论经常被当成事件分析总结"],
    traits: ["民间法官","逻辑分析达人","证据收集者","网络判官","真相追寻者"],
    suggestions: "你的分析能力是稀缺资源——在假消息满天飞的时代，能理性分析的人越来越少。"
  },
  {
    code: "shuziyouling",
    name: "数字幽灵",
    emoji: "👤",
    rarity: "传说",
    cluster: "introvert",
    pattern: { So: "L", E: "L", Ac: "L", N: "L" },
    desc: "你在网络上几乎不存在——没有社交媒体账号，或者有但从来没有发过任何内容。",
    common_comments: ["你能帮我搜一下XX吗？", "你的社交媒体账号就像一个摆设"],
    traits: ["在线透明人","网络隐士","低存在感","不社交主义者","极简社交"],
    suggestions: "你选择了一种极端低信息化的生活方式，这在一个被网络裹挟的世界里是一种勇气。"
  }
];
